version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`localhost`)"
      - "traefik.http.routers.web.entrypoints=web"
    networks:
      traefik:

networks:
  traefik:
    external:
      name: traefik
