version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    environment:
      - PORT=80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`www.emotives.net`)"
      - "traefik.http.routers.web.tls=true"
      - "traefik.http.routers.web.tls.certresolver=letsencrypt"
    networks:
      traefik:

networks:
  traefik:
    external:
      name: traefik
