version: '3.7'

services:
  web:
    image: ghcr.io/tombowyerresearchproject/web:latest
    environment:
      - PORT=80
      - REACT_APP_API_HOST=https
      - REACT_APP_WS_HOST=wss
      - REACT_APP_UACL_BASE_URL=uacl.emotives.net
      - REACT_APP_POSTIT_BASE_URL=postit.emotives.net
      - REACT_APP_CHATTER_BASE_URL=chatter.emotives.net
      - REACT_APP_NOTIF_BASE_URL=notif.emotives.net
      - REACT_APP_MEDIA_BASE_URL=media.emotives.net
      - REACT_APP_MEDIA_UPLOAD_BASE_URL=media-upload.emotives.net
      - REACT_APP_GOOGLE_KEY="${REACT_APP_GOOGLE_KEY:?}""
      - STORYBOOK_RUN=false
    restart: unless-stopped
    logging:
      driver: syslog
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`www.emotives.net`) || Host(`emotives.net`)"
      - "traefik.http.routers.web.tls=true"
      - "traefik.http.routers.web.tls.certresolver=letsencrypt"
    networks:
      traefik:

networks:
  traefik:
    external:
      name: traefik
