version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`www.emotives.net`)"
      - "traefik.http.routers.fastapi.tls=true"
      - "traefik.http.routers.fastapi.tls.certresolver=letsencrypt"
    networks:
      traefik:

networks:
  traefik:
    external:
      name: traefik
