version: '3.7'

services:
  web:
    image: ghcr.io/tombowyerresearchproject/web:latest
    environment:
      - PORT=80
    restart: unless-stopped
    logging:
      driver: syslog
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`www.emotives.net`) || Host(`emotives.net`)"
      - "traefik.http.routers.web.tls=true"
      - "traefik.http.routers.web.tls.certresolver=letsencrypt"
    networks:
      traefik:

networks:
  traefik:
    external:
      name: traefik
