version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true
      - PORT=80
      - REACT_APP_API_HOST=http
      - REACT_APP_WS_HOST=ws
      - REACT_APP_UACL_BASE_URL=uacl.localhost
      - REACT_APP_POSTIT_BASE_URL=postit.localhost
      - REACT_APP_CHATTER_BASE_URL=chatter.localhost
      - REACT_APP_NOTIF_BASE_URL=notif.localhost
      - REACT_APP_MEDIA_BASE_URL=media.localhost
      - REACT_APP_MEDIA_UPLOAD_BASE_URL=media-upload.localhost
      - REACT_APP_GOOGLE_KEY=AIzaSyBu8MhwdgcqLbliyFs4wS9QzgQMWuhaq4A
      - STORYBOOK_RUN=false
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`localhost`)"
      - "traefik.http.routers.web.entrypoints=web"
    networks:
      traefik:

networks:
  traefik:
    external:
      name: traefik